apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - prod
  containers:
  - name: nginx-1
    image: nginx:stable-perl
